package com.hkm.stickhub.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Batch-B theme tokens: Kawaii, Solarpunk, Noir, Glass, Nouveau.
 * Every scheme carries explicit opaque surface-container roles so
 * ModalBottomSheet / AlertDialog never render transparent.
 */

// ---------------------------------------------------------------- Kawaii ---
object KawaiiColors {
    val LightCandyBackground = Color(0xFFFFD1DC)
    val LightCreamSurface = Color(0xFFFFF9FB)
    val LightBlushSurfaceVariant = Color(0xFFF7E4EC)
    val LightGrapePrimary = Color(0xFF8E44AD)
    val LightOnPrimary = Color(0xFFFFFFFF)
    val LightPetalPrimaryContainer = Color(0xFFF8D7E6)
    val LightOnPetalContainer = Color(0xFF5E2A52)
    val LightSkySecondary = Color(0xFF2F7FA8)
    val LightOnSecondary = Color(0xFFFFFFFF)
    val LightBabySecondaryContainer = Color(0xFFB3E5FC)
    val LightOnSecondaryContainer = Color(0xFF0E3A4F)
    val LightMintTertiary = Color(0xFF2E9E63)
    val LightOnTertiary = Color(0xFFFFFFFF)
    val LightMintTertiaryContainer = Color(0xFFB9F6CA)
    val LightOnTertiaryContainer = Color(0xFF0C3A22)
    val LightCocoaText = Color(0xFF3A2A33)
    val LightMutedText = Color(0xFF8A7384)
    val LightRoseOutline = Color(0xFFCE8FA8)
    val LightSoftOutlineVariant = Color(0xFFF0D3E0)
    val LightError = Color(0xFFB5404F)
    val LightOnError = Color(0xFFFFFFFF)
    val LightErrorContainer = Color(0xFFF6D3DA)
    val LightOnErrorContainer = Color(0xFF410002)

    val DarkGrapeBackground = Color(0xFF2A1E2E)
    val DarkGrapeSurface = Color(0xFF372839)
    val DarkGrapeSurfaceVariant = Color(0xFF4A3550)
    val DarkCandyPrimary = Color(0xFFFFB3D1)
    val DarkOnPrimary = Color(0xFF4A1E38)
    val DarkPlumPrimaryContainer = Color(0xFF6E3560)
    val DarkOnPrimaryContainer = Color(0xFFFFD9E8)
    val DarkSkySecondary = Color(0xFF9BDCFA)
    val DarkOnSecondary = Color(0xFF0E3A4F)
    val DarkNavySecondaryContainer = Color(0xFF1E4A66)
    val DarkOnSecondaryContainer = Color(0xFFCDEFFD)
    val DarkMintTertiary = Color(0xFF8FF0B8)
    val DarkOnTertiary = Color(0xFF0C3A22)
    val DarkForestTertiaryContainer = Color(0xFF14532E)
    val DarkOnTertiaryContainer = Color(0xFFC9F5D6)
    val DarkSugarText = Color(0xFFFBE9F2)
    val DarkMutedText = Color(0xFFC4A8BC)
    val DarkRoseOutline = Color(0xFFB07A9E)
    val DarkSoftOutlineVariant = Color(0xFF54405A)
    val DarkError = Color(0xFFF0839B)
    val DarkOnError = Color(0xFF4A0E1E)
    val DarkErrorContainer = Color(0xFF5C2233)
    val DarkOnErrorContainer = Color(0xFFFFD9E2)
}

val KawaiiLightColorScheme: ColorScheme = lightColorScheme(
    primary = KawaiiColors.LightGrapePrimary,
    onPrimary = KawaiiColors.LightOnPrimary,
    primaryContainer = KawaiiColors.LightPetalPrimaryContainer,
    onPrimaryContainer = KawaiiColors.LightOnPetalContainer,
    secondary = KawaiiColors.LightSkySecondary,
    onSecondary = KawaiiColors.LightOnSecondary,
    secondaryContainer = KawaiiColors.LightBabySecondaryContainer,
    onSecondaryContainer = KawaiiColors.LightOnSecondaryContainer,
    tertiary = KawaiiColors.LightMintTertiary,
    onTertiary = KawaiiColors.LightOnTertiary,
    tertiaryContainer = KawaiiColors.LightMintTertiaryContainer,
    onTertiaryContainer = KawaiiColors.LightOnTertiaryContainer,
    background = KawaiiColors.LightCandyBackground,
    onBackground = KawaiiColors.LightCocoaText,
    surface = KawaiiColors.LightCreamSurface,
    onSurface = KawaiiColors.LightCocoaText,
    surfaceVariant = KawaiiColors.LightBlushSurfaceVariant,
    onSurfaceVariant = KawaiiColors.LightMutedText,
    outline = KawaiiColors.LightRoseOutline,
    outlineVariant = KawaiiColors.LightSoftOutlineVariant,
    error = KawaiiColors.LightError,
    onError = KawaiiColors.LightOnError,
    errorContainer = KawaiiColors.LightErrorContainer,
    onErrorContainer = KawaiiColors.LightOnErrorContainer,
    surfaceBright = KawaiiColors.LightCreamSurface,
    surfaceDim = KawaiiColors.LightBlushSurfaceVariant,
    surfaceContainerLowest = KawaiiColors.LightCreamSurface,
    surfaceContainerLow = KawaiiColors.LightCreamSurface,
    surfaceContainer = KawaiiColors.LightBlushSurfaceVariant,
    surfaceContainerHigh = KawaiiColors.LightBlushSurfaceVariant,
    surfaceContainerHighest = KawaiiColors.LightBlushSurfaceVariant
)

val KawaiiDarkColorScheme: ColorScheme = darkColorScheme(
    primary = KawaiiColors.DarkCandyPrimary,
    onPrimary = KawaiiColors.DarkOnPrimary,
    primaryContainer = KawaiiColors.DarkPlumPrimaryContainer,
    onPrimaryContainer = KawaiiColors.DarkOnPrimaryContainer,
    secondary = KawaiiColors.DarkSkySecondary,
    onSecondary = KawaiiColors.DarkOnSecondary,
    secondaryContainer = KawaiiColors.DarkNavySecondaryContainer,
    onSecondaryContainer = KawaiiColors.DarkOnSecondaryContainer,
    tertiary = KawaiiColors.DarkMintTertiary,
    onTertiary = KawaiiColors.DarkOnTertiary,
    tertiaryContainer = KawaiiColors.DarkForestTertiaryContainer,
    onTertiaryContainer = KawaiiColors.DarkOnTertiaryContainer,
    background = KawaiiColors.DarkGrapeBackground,
    onBackground = KawaiiColors.DarkSugarText,
    surface = KawaiiColors.DarkGrapeSurface,
    onSurface = KawaiiColors.DarkSugarText,
    surfaceVariant = KawaiiColors.DarkGrapeSurfaceVariant,
    onSurfaceVariant = KawaiiColors.DarkMutedText,
    outline = KawaiiColors.DarkRoseOutline,
    outlineVariant = KawaiiColors.DarkSoftOutlineVariant,
    error = KawaiiColors.DarkError,
    onError = KawaiiColors.DarkOnError,
    errorContainer = KawaiiColors.DarkErrorContainer,
    onErrorContainer = KawaiiColors.DarkOnErrorContainer,
    surfaceBright = KawaiiColors.DarkGrapeSurfaceVariant,
    surfaceDim = KawaiiColors.DarkGrapeSurface,
    surfaceContainerLowest = KawaiiColors.DarkGrapeSurface,
    surfaceContainerLow = KawaiiColors.DarkGrapeSurface,
    surfaceContainer = KawaiiColors.DarkGrapeSurfaceVariant,
    surfaceContainerHigh = KawaiiColors.DarkGrapeSurfaceVariant,
    surfaceContainerHighest = KawaiiColors.DarkGrapeSurfaceVariant
)

// -------------------------------------------------------------- Solarpunk ---
object SolarpunkColors {
    val LightMorningBackground = Color(0xFFFFF8E7)
    val LightCanopySurface = Color(0xFFFFFFFF)
    val LightHaySurfaceVariant = Color(0xFFF2EAD2)
    val LightVerdantPrimary = Color(0xFF2D6A4F)
    val LightOnPrimary = Color(0xFFFFFFFF)
    val LightLeafPrimaryContainer = Color(0xFFC9E6CF)
    val LightOnLeafContainer = Color(0xFF123B28)
    val LightHarvestSecondary = Color(0xFFA66E00)
    val LightOnSecondary = Color(0xFFFFFFFF)
    val LightHoneySecondaryContainer = Color(0xFFFFE0A3)
    val LightOnSecondaryContainer = Color(0xFF3F2C00)
    val LightSkyTertiary = Color(0xFF147A94)
    val LightOnTertiary = Color(0xFFFFFFFF)
    val LightCloudTertiaryContainer = Color(0xFFC5E9F2)
    val LightOnTertiaryContainer = Color(0xFF0B3542)
    val LightSoilText = Color(0xFF1E2A22)
    val LightMutedText = Color(0xFF5F6F62)
    val LightVineOutline = Color(0xFF6FA287)
    val LightSoftOutlineVariant = Color(0xFFD3E2D2)
    val LightError = Color(0xFFA63A32)
    val LightOnError = Color(0xFFFFFFFF)
    val LightErrorContainer = Color(0xFFF5D5D1)
    val LightOnErrorContainer = Color(0xFF410002)

    val DarkForestBackground = Color(0xFF0E241B)
    val DarkCanopySurface = Color(0xFF153324)
    val DarkCanopySurfaceVariant = Color(0xFF1C4030)
    val DarkSproutPrimary = Color(0xFF6FD89C)
    val DarkOnPrimary = Color(0xFF0E241B)
    val DarkGrovePrimaryContainer = Color(0xFF1D4A33)
    val DarkOnPrimaryContainer = Color(0xFFD2F0DA)
    val DarkSolarSecondary = Color(0xFFFFB703)
    val DarkOnSecondary = Color(0xFF0E241B)
    val DarkAmberSecondaryContainer = Color(0xFF4A3200)
    val DarkOnSecondaryContainer = Color(0xFFFFE3A1)
    val DarkSkyTertiary = Color(0xFF7FD4EC)
    val DarkOnTertiary = Color(0xFF0B3542)
    val DarkLagoonTertiaryContainer = Color(0xFF134A5C)
    val DarkOnTertiaryContainer = Color(0xFFC5E9F2)
    val DarkDewText = Color(0xFFEAF5E9)
    val DarkMutedText = Color(0xFFA4BFA8)
    val DarkVineOutline = Color(0xFF4E7A5E)
    val DarkSoftOutlineVariant = Color(0xFF24402F)
    val DarkError = Color(0xFFE89890)
    val DarkOnError = Color(0xFF3A0E0B)
    val DarkErrorContainer = Color(0xFF5C2222)
    val DarkOnErrorContainer = Color(0xFFFFD9D9)
}

val SolarpunkLightColorScheme: ColorScheme = lightColorScheme(
    primary = SolarpunkColors.LightVerdantPrimary,
    onPrimary = SolarpunkColors.LightOnPrimary,
    primaryContainer = SolarpunkColors.LightLeafPrimaryContainer,
    onPrimaryContainer = SolarpunkColors.LightOnLeafContainer,
    secondary = SolarpunkColors.LightHarvestSecondary,
    onSecondary = SolarpunkColors.LightOnSecondary,
    secondaryContainer = SolarpunkColors.LightHoneySecondaryContainer,
    onSecondaryContainer = SolarpunkColors.LightOnSecondaryContainer,
    tertiary = SolarpunkColors.LightSkyTertiary,
    onTertiary = SolarpunkColors.LightOnTertiary,
    tertiaryContainer = SolarpunkColors.LightCloudTertiaryContainer,
    onTertiaryContainer = SolarpunkColors.LightOnTertiaryContainer,
    background = SolarpunkColors.LightMorningBackground,
    onBackground = SolarpunkColors.LightSoilText,
    surface = SolarpunkColors.LightCanopySurface,
    onSurface = SolarpunkColors.LightSoilText,
    surfaceVariant = SolarpunkColors.LightHaySurfaceVariant,
    onSurfaceVariant = SolarpunkColors.LightMutedText,
    outline = SolarpunkColors.LightVineOutline,
    outlineVariant = SolarpunkColors.LightSoftOutlineVariant,
    error = SolarpunkColors.LightError,
    onError = SolarpunkColors.LightOnError,
    errorContainer = SolarpunkColors.LightErrorContainer,
    onErrorContainer = SolarpunkColors.LightOnErrorContainer,
    surfaceBright = SolarpunkColors.LightCanopySurface,
    surfaceDim = SolarpunkColors.LightHaySurfaceVariant,
    surfaceContainerLowest = SolarpunkColors.LightCanopySurface,
    surfaceContainerLow = SolarpunkColors.LightCanopySurface,
    surfaceContainer = SolarpunkColors.LightHaySurfaceVariant,
    surfaceContainerHigh = SolarpunkColors.LightHaySurfaceVariant,
    surfaceContainerHighest = SolarpunkColors.LightHaySurfaceVariant
)

val SolarpunkDarkColorScheme: ColorScheme = darkColorScheme(
    primary = SolarpunkColors.DarkSproutPrimary,
    onPrimary = SolarpunkColors.DarkOnPrimary,
    primaryContainer = SolarpunkColors.DarkGrovePrimaryContainer,
    onPrimaryContainer = SolarpunkColors.DarkOnPrimaryContainer,
    secondary = SolarpunkColors.DarkSolarSecondary,
    onSecondary = SolarpunkColors.DarkOnSecondary,
    secondaryContainer = SolarpunkColors.DarkAmberSecondaryContainer,
    onSecondaryContainer = SolarpunkColors.DarkOnSecondaryContainer,
    tertiary = SolarpunkColors.DarkSkyTertiary,
    onTertiary = SolarpunkColors.DarkOnTertiary,
    tertiaryContainer = SolarpunkColors.DarkLagoonTertiaryContainer,
    onTertiaryContainer = SolarpunkColors.DarkOnTertiaryContainer,
    background = SolarpunkColors.DarkForestBackground,
    onBackground = SolarpunkColors.DarkDewText,
    surface = SolarpunkColors.DarkCanopySurface,
    onSurface = SolarpunkColors.DarkDewText,
    surfaceVariant = SolarpunkColors.DarkCanopySurfaceVariant,
    onSurfaceVariant = SolarpunkColors.DarkMutedText,
    outline = SolarpunkColors.DarkVineOutline,
    outlineVariant = SolarpunkColors.DarkSoftOutlineVariant,
    error = SolarpunkColors.DarkError,
    onError = SolarpunkColors.DarkOnError,
    errorContainer = SolarpunkColors.DarkErrorContainer,
    onErrorContainer = SolarpunkColors.DarkOnErrorContainer,
    surfaceBright = SolarpunkColors.DarkCanopySurfaceVariant,
    surfaceDim = SolarpunkColors.DarkCanopySurface,
    surfaceContainerLowest = SolarpunkColors.DarkCanopySurface,
    surfaceContainerLow = SolarpunkColors.DarkCanopySurface,
    surfaceContainer = SolarpunkColors.DarkCanopySurfaceVariant,
    surfaceContainerHigh = SolarpunkColors.DarkCanopySurfaceVariant,
    surfaceContainerHighest = SolarpunkColors.DarkCanopySurfaceVariant
)

// ------------------------------------------------------------------ Noir ---
object NoirColors {
    val LightDossierBackground = Color(0xFFE8E0D0)
    val LightCaseSurface = Color(0xFFF4EDDE)
    val LightManilaSurfaceVariant = Color(0xFFD9CBAE)
    val LightInkPrimary = Color(0xFF232323)
    val LightOnPrimary = Color(0xFFE8E0D0)
    val LightFogPrimaryContainer = Color(0xFFD4D4D4)
    val LightOnFogContainer = Color(0xFF232323)
    val LightStreetlampSecondary = Color(0xFF8A6410)
    val LightOnSecondary = Color(0xFFF4EDDE)
    val LightBulbSecondaryContainer = Color(0xFFF0D98A)
    val LightOnSecondaryContainer = Color(0xFF3A2C04)
    val LightWineTertiary = Color(0xFF6E1414)
    val LightOnTertiary = Color(0xFFF4EDDE)
    val LightStainTertiaryContainer = Color(0xFFE3B8B8)
    val LightOnTertiaryContainer = Color(0xFF3A0D0D)
    val LightInkText = Color(0xFF232323)
    val LightMutedText = Color(0xFF6E6259)
    val LightSmokeOutline = Color(0xFF4A4A4A)
    val LightSoftOutlineVariant = Color(0xFFC4B89E)
    val LightError = Color(0xFF9E2B22)
    val LightOnError = Color(0xFFF4EDDE)
    val LightErrorContainer = Color(0xFFF2CDC7)
    val LightOnErrorContainer = Color(0xFF410002)

    val DarkAlleyBackground = Color(0xFF111113)
    val DarkOfficeSurface = Color(0xFF1A1A1E)
    val DarkOfficeSurfaceVariant = Color(0xFF26262C)
    val DarkFogPrimary = Color(0xFFD4D4D4)
    val DarkOnPrimary = Color(0xFF111113)
    val DarkSmokePrimaryContainer = Color(0xFF3A3A42)
    val DarkOnPrimaryContainer = Color(0xFFE8E8E8)
    val DarkStreetlampSecondary = Color(0xFFE8C547)
    val DarkOnSecondary = Color(0xFF111113)
    val DarkAmberSecondaryContainer = Color(0xFF4A3A08)
    val DarkOnSecondaryContainer = Color(0xFFF0D98A)
    val DarkWineTertiary = Color(0xFFA83232)
    val DarkOnTertiary = Color(0xFFFFF0EC)
    val DarkCellarTertiaryContainer = Color(0xFF3A0D0D)
    val DarkOnTertiaryContainer = Color(0xFFE3B8B8)
    val DarkFogText = Color(0xFFD4D4D4)
    val DarkMutedText = Color(0xFF8E8E96)
    val DarkSmokeOutline = Color(0xFF4A4A4A)
    val DarkSoftOutlineVariant = Color(0xFF2E2E34)
    val DarkError = Color(0xFFFF5A4E)
    val DarkOnError = Color(0xFF111113)
    val DarkErrorContainer = Color(0xFF5C1A14)
    val DarkOnErrorContainer = Color(0xFFFFC9C2)
}

val NoirLightColorScheme: ColorScheme = lightColorScheme(
    primary = NoirColors.LightInkPrimary,
    onPrimary = NoirColors.LightOnPrimary,
    primaryContainer = NoirColors.LightFogPrimaryContainer,
    onPrimaryContainer = NoirColors.LightOnFogContainer,
    secondary = NoirColors.LightStreetlampSecondary,
    onSecondary = NoirColors.LightOnSecondary,
    secondaryContainer = NoirColors.LightBulbSecondaryContainer,
    onSecondaryContainer = NoirColors.LightOnSecondaryContainer,
    tertiary = NoirColors.LightWineTertiary,
    onTertiary = NoirColors.LightOnTertiary,
    tertiaryContainer = NoirColors.LightStainTertiaryContainer,
    onTertiaryContainer = NoirColors.LightOnTertiaryContainer,
    background = NoirColors.LightDossierBackground,
    onBackground = NoirColors.LightInkText,
    surface = NoirColors.LightCaseSurface,
    onSurface = NoirColors.LightInkText,
    surfaceVariant = NoirColors.LightManilaSurfaceVariant,
    onSurfaceVariant = NoirColors.LightMutedText,
    outline = NoirColors.LightSmokeOutline,
    outlineVariant = NoirColors.LightSoftOutlineVariant,
    error = NoirColors.LightError,
    onError = NoirColors.LightOnError,
    errorContainer = NoirColors.LightErrorContainer,
    onErrorContainer = NoirColors.LightOnErrorContainer,
    surfaceBright = NoirColors.LightCaseSurface,
    surfaceDim = NoirColors.LightManilaSurfaceVariant,
    surfaceContainerLowest = NoirColors.LightCaseSurface,
    surfaceContainerLow = NoirColors.LightCaseSurface,
    surfaceContainer = NoirColors.LightManilaSurfaceVariant,
    surfaceContainerHigh = NoirColors.LightManilaSurfaceVariant,
    surfaceContainerHighest = NoirColors.LightManilaSurfaceVariant
)

val NoirDarkColorScheme: ColorScheme = darkColorScheme(
    primary = NoirColors.DarkFogPrimary,
    onPrimary = NoirColors.DarkOnPrimary,
    primaryContainer = NoirColors.DarkSmokePrimaryContainer,
    onPrimaryContainer = NoirColors.DarkOnPrimaryContainer,
    secondary = NoirColors.DarkStreetlampSecondary,
    onSecondary = NoirColors.DarkOnSecondary,
    secondaryContainer = NoirColors.DarkAmberSecondaryContainer,
    onSecondaryContainer = NoirColors.DarkOnSecondaryContainer,
    tertiary = NoirColors.DarkWineTertiary,
    onTertiary = NoirColors.DarkOnTertiary,
    tertiaryContainer = NoirColors.DarkCellarTertiaryContainer,
    onTertiaryContainer = NoirColors.DarkOnTertiaryContainer,
    background = NoirColors.DarkAlleyBackground,
    onBackground = NoirColors.DarkFogText,
    surface = NoirColors.DarkOfficeSurface,
    onSurface = NoirColors.DarkFogText,
    surfaceVariant = NoirColors.DarkOfficeSurfaceVariant,
    onSurfaceVariant = NoirColors.DarkMutedText,
    outline = NoirColors.DarkSmokeOutline,
    outlineVariant = NoirColors.DarkSoftOutlineVariant,
    error = NoirColors.DarkError,
    onError = NoirColors.DarkOnError,
    errorContainer = NoirColors.DarkErrorContainer,
    onErrorContainer = NoirColors.DarkOnErrorContainer,
    surfaceBright = NoirColors.DarkOfficeSurfaceVariant,
    surfaceDim = NoirColors.DarkOfficeSurface,
    surfaceContainerLowest = NoirColors.DarkOfficeSurface,
    surfaceContainerLow = NoirColors.DarkOfficeSurface,
    surfaceContainer = NoirColors.DarkOfficeSurfaceVariant,
    surfaceContainerHigh = NoirColors.DarkOfficeSurfaceVariant,
    surfaceContainerHighest = NoirColors.DarkOfficeSurfaceVariant
)

// ----------------------------------------------------------------- Glass ---
object GlassColors {
    val LightSkylightBackground = Color(0xFFE9EEFB)
    val LightPaneSurface = Color(0xFFF4F7FF)
    val LightMistSurfaceVariant = Color(0xFFE2E9FB)
    val LightCobaltPrimary = Color(0xFF0066FF)
    val LightOnPrimary = Color(0xFFFFFFFF)
    val LightIcePrimaryContainer = Color(0xFFD6E4FF)
    val LightOnIceContainer = Color(0xFF002B66)
    val LightIrisSecondary = Color(0xFF6C5CE7)
    val LightOnSecondary = Color(0xFFFFFFFF)
    val LightHazeSecondaryContainer = Color(0xFFE2DAFF)
    val LightOnSecondaryContainer = Color(0xFF2E2270)
    val LightCyanTertiary = Color(0xFF0090B3)
    val LightOnTertiary = Color(0xFFFFFFFF)
    val LightGlacierTertiaryContainer = Color(0xFFC2EEF7)
    val LightOnTertiaryContainer = Color(0xFF063A47)
    val LightInkText = Color(0xFF141A2E)
    val LightMutedText = Color(0xFF5C667F)
    val LightGlassOutline = Color(0xFFB9C6E8)
    val LightSoftOutlineVariant = Color(0xFFDCE4F7)
    val LightError = Color(0xFFC2263C)
    val LightOnError = Color(0xFFFFFFFF)
    val LightErrorContainer = Color(0xFFF6D2D8)
    val LightOnErrorContainer = Color(0xFF410002)

    val DarkAbyssBackground = Color(0xFF0B1026)
    val DarkPaneSurface = Color(0xFF141B38)
    val DarkPaneSurfaceVariant = Color(0xFF1E2750)
    val DarkBeamPrimary = Color(0xFF66A3FF)
    val DarkOnPrimary = Color(0xFF0B1026)
    val DarkHarborPrimaryContainer = Color(0xFF1E3A7A)
    val DarkOnPrimaryContainer = Color(0xFFD6E4FF)
    val DarkIrisSecondary = Color(0xFFA78BFA)
    val DarkOnSecondary = Color(0xFF0B1026)
    val DarkNebulaSecondaryContainer = Color(0xFF3B2E7A)
    val DarkOnSecondaryContainer = Color(0xFFE2DAFF)
    val DarkCyanTertiary = Color(0xFF67E8F9)
    val DarkOnTertiary = Color(0xFF063A47)
    val DarkLagoonTertiaryContainer = Color(0xFF0E4A5C)
    val DarkOnTertiaryContainer = Color(0xFFC2EEF7)
    val DarkFrostText = Color(0xFFE9EEFB)
    val DarkMutedText = Color(0xFF9AA6C8)
    val DarkGlassOutline = Color(0xFF5A6B9E)
    val DarkSoftOutlineVariant = Color(0xFF2A3560)
    val DarkError = Color(0xFFFF6B7A)
    val DarkOnError = Color(0xFF0B1026)
    val DarkErrorContainer = Color(0xFF5C2233)
    val DarkOnErrorContainer = Color(0xFFFFD9E2)
}

val GlassLightColorScheme: ColorScheme = lightColorScheme(
    primary = GlassColors.LightCobaltPrimary,
    onPrimary = GlassColors.LightOnPrimary,
    primaryContainer = GlassColors.LightIcePrimaryContainer,
    onPrimaryContainer = GlassColors.LightOnIceContainer,
    secondary = GlassColors.LightIrisSecondary,
    onSecondary = GlassColors.LightOnSecondary,
    secondaryContainer = GlassColors.LightHazeSecondaryContainer,
    onSecondaryContainer = GlassColors.LightOnSecondaryContainer,
    tertiary = GlassColors.LightCyanTertiary,
    onTertiary = GlassColors.LightOnTertiary,
    tertiaryContainer = GlassColors.LightGlacierTertiaryContainer,
    onTertiaryContainer = GlassColors.LightOnTertiaryContainer,
    background = GlassColors.LightSkylightBackground,
    onBackground = GlassColors.LightInkText,
    surface = GlassColors.LightPaneSurface,
    onSurface = GlassColors.LightInkText,
    surfaceVariant = GlassColors.LightMistSurfaceVariant,
    onSurfaceVariant = GlassColors.LightMutedText,
    outline = GlassColors.LightGlassOutline,
    outlineVariant = GlassColors.LightSoftOutlineVariant,
    error = GlassColors.LightError,
    onError = GlassColors.LightOnError,
    errorContainer = GlassColors.LightErrorContainer,
    onErrorContainer = GlassColors.LightOnErrorContainer,
    surfaceBright = GlassColors.LightPaneSurface,
    surfaceDim = GlassColors.LightMistSurfaceVariant,
    surfaceContainerLowest = GlassColors.LightPaneSurface,
    surfaceContainerLow = GlassColors.LightPaneSurface,
    surfaceContainer = GlassColors.LightMistSurfaceVariant,
    surfaceContainerHigh = GlassColors.LightMistSurfaceVariant,
    surfaceContainerHighest = GlassColors.LightMistSurfaceVariant
)

val GlassDarkColorScheme: ColorScheme = darkColorScheme(
    primary = GlassColors.DarkBeamPrimary,
    onPrimary = GlassColors.DarkOnPrimary,
    primaryContainer = GlassColors.DarkHarborPrimaryContainer,
    onPrimaryContainer = GlassColors.DarkOnPrimaryContainer,
    secondary = GlassColors.DarkIrisSecondary,
    onSecondary = GlassColors.DarkOnSecondary,
    secondaryContainer = GlassColors.DarkNebulaSecondaryContainer,
    onSecondaryContainer = GlassColors.DarkOnSecondaryContainer,
    tertiary = GlassColors.DarkCyanTertiary,
    onTertiary = GlassColors.DarkOnTertiary,
    tertiaryContainer = GlassColors.DarkLagoonTertiaryContainer,
    onTertiaryContainer = GlassColors.DarkOnTertiaryContainer,
    background = GlassColors.DarkAbyssBackground,
    onBackground = GlassColors.DarkFrostText,
    surface = GlassColors.DarkPaneSurface,
    onSurface = GlassColors.DarkFrostText,
    surfaceVariant = GlassColors.DarkPaneSurfaceVariant,
    onSurfaceVariant = GlassColors.DarkMutedText,
    outline = GlassColors.DarkGlassOutline,
    outlineVariant = GlassColors.DarkSoftOutlineVariant,
    error = GlassColors.DarkError,
    onError = GlassColors.DarkOnError,
    errorContainer = GlassColors.DarkErrorContainer,
    onErrorContainer = GlassColors.DarkOnErrorContainer,
    surfaceBright = GlassColors.DarkPaneSurfaceVariant,
    surfaceDim = GlassColors.DarkPaneSurface,
    surfaceContainerLowest = GlassColors.DarkPaneSurface,
    surfaceContainerLow = GlassColors.DarkPaneSurface,
    surfaceContainer = GlassColors.DarkPaneSurfaceVariant,
    surfaceContainerHigh = GlassColors.DarkPaneSurfaceVariant,
    surfaceContainerHighest = GlassColors.DarkPaneSurfaceVariant
)

// --------------------------------------------------------------- Nouveau ---
object NouveauColors {
    val LightIvoryBackground = Color(0xFFFFFFF0)
    val LightGallerySurface = Color(0xFFFFFDF5)
    val LightParchmentSurfaceVariant = Color(0xFFF5EDD8)
    val LightDeepTealPrimary = Color(0xFF006B6B)
    val LightOnPrimary = Color(0xFFFFFFFF)
    val LightLagoonPrimaryContainer = Color(0xFFC6E3DE)
    val LightOnLagoonContainer = Color(0xFF063B3B)
    val LightOldGoldSecondary = Color(0xFF8A6D1B)
    val LightOnSecondary = Color(0xFFFFFFFF)
    val LightGiltSecondaryContainer = Color(0xFFF0E3B8)
    val LightOnSecondaryContainer = Color(0xFF3A2D05)
    val LightBurgundyTertiary = Color(0xFF8E1F38)
    val LightOnTertiary = Color(0xFFFFFFFF)
    val LightRoseTertiaryContainer = Color(0xFFF0CBD4)
    val LightOnTertiaryContainer = Color(0xFF400A18)
    val LightInkText = Color(0xFF2E2A20)
    val LightMutedText = Color(0xFF6E675A)
    val LightGoldOutline = Color(0xFFA98F3E)
    val LightSoftOutlineVariant = Color(0xFFE3D5AE)
    val LightError = Color(0xFFA63A32)
    val LightOnError = Color(0xFFFFFFFF)
    val LightErrorContainer = Color(0xFFF5D5D1)
    val LightOnErrorContainer = Color(0xFF410002)

    val DarkLagoonBackground = Color(0xFF0E2A28)
    val DarkLagoonSurface = Color(0xFF123836)
    val DarkLagoonSurfaceVariant = Color(0xFF1B4A46)
    val DarkSeafoamPrimary = Color(0xFF5ABFB8)
    val DarkOnPrimary = Color(0xFF0E2A28)
    val DarkReefPrimaryContainer = Color(0xFF155E59)
    val DarkOnPrimaryContainer = Color(0xFFC6E3DE)
    val DarkGoldSecondary = Color(0xFFCFB53B)
    val DarkOnSecondary = Color(0xFF0E2A28)
    val DarkBronzeSecondaryContainer = Color(0xFF4A3D10)
    val DarkOnSecondaryContainer = Color(0xFFF0E3B8)
    val DarkMauveTertiary = Color(0xFFD9A8F5)
    val DarkOnTertiary = Color(0xFF2E1440)
    val DarkPlumTertiaryContainer = Color(0xFF40255C)
    val DarkOnTertiaryContainer = Color(0xFFE7CBFA)
    val DarkIvoryText = Color(0xFFF2EDDC)
    val DarkMutedText = Color(0xFFB3AA93)
    val DarkGoldOutline = Color(0xFFB89B4A)
    val DarkSoftOutlineVariant = Color(0xFF2E4A44)
    val DarkError = Color(0xFFE89890)
    val DarkOnError = Color(0xFF3A0E0B)
    val DarkErrorContainer = Color(0xFF5C2222)
    val DarkOnErrorContainer = Color(0xFFFFD9D9)
}

val NouveauLightColorScheme: ColorScheme = lightColorScheme(
    primary = NouveauColors.LightDeepTealPrimary,
    onPrimary = NouveauColors.LightOnPrimary,
    primaryContainer = NouveauColors.LightLagoonPrimaryContainer,
    onPrimaryContainer = NouveauColors.LightOnLagoonContainer,
    secondary = NouveauColors.LightOldGoldSecondary,
    onSecondary = NouveauColors.LightOnSecondary,
    secondaryContainer = NouveauColors.LightGiltSecondaryContainer,
    onSecondaryContainer = NouveauColors.LightOnSecondaryContainer,
    tertiary = NouveauColors.LightBurgundyTertiary,
    onTertiary = NouveauColors.LightOnTertiary,
    tertiaryContainer = NouveauColors.LightRoseTertiaryContainer,
    onTertiaryContainer = NouveauColors.LightOnTertiaryContainer,
    background = NouveauColors.LightIvoryBackground,
    onBackground = NouveauColors.LightInkText,
    surface = NouveauColors.LightGallerySurface,
    onSurface = NouveauColors.LightInkText,
    surfaceVariant = NouveauColors.LightParchmentSurfaceVariant,
    onSurfaceVariant = NouveauColors.LightMutedText,
    outline = NouveauColors.LightGoldOutline,
    outlineVariant = NouveauColors.LightSoftOutlineVariant,
    error = NouveauColors.LightError,
    onError = NouveauColors.LightOnError,
    errorContainer = NouveauColors.LightErrorContainer,
    onErrorContainer = NouveauColors.LightOnErrorContainer,
    surfaceBright = NouveauColors.LightGallerySurface,
    surfaceDim = NouveauColors.LightParchmentSurfaceVariant,
    surfaceContainerLowest = NouveauColors.LightGallerySurface,
    surfaceContainerLow = NouveauColors.LightGallerySurface,
    surfaceContainer = NouveauColors.LightParchmentSurfaceVariant,
    surfaceContainerHigh = NouveauColors.LightParchmentSurfaceVariant,
    surfaceContainerHighest = NouveauColors.LightParchmentSurfaceVariant
)

val NouveauDarkColorScheme: ColorScheme = darkColorScheme(
    primary = NouveauColors.DarkSeafoamPrimary,
    onPrimary = NouveauColors.DarkOnPrimary,
    primaryContainer = NouveauColors.DarkReefPrimaryContainer,
    onPrimaryContainer = NouveauColors.DarkOnPrimaryContainer,
    secondary = NouveauColors.DarkGoldSecondary,
    onSecondary = NouveauColors.DarkOnSecondary,
    secondaryContainer = NouveauColors.DarkBronzeSecondaryContainer,
    onSecondaryContainer = NouveauColors.DarkOnSecondaryContainer,
    tertiary = NouveauColors.DarkMauveTertiary,
    onTertiary = NouveauColors.DarkOnTertiary,
    tertiaryContainer = NouveauColors.DarkPlumTertiaryContainer,
    onTertiaryContainer = NouveauColors.DarkOnTertiaryContainer,
    background = NouveauColors.DarkLagoonBackground,
    onBackground = NouveauColors.DarkIvoryText,
    surface = NouveauColors.DarkLagoonSurface,
    onSurface = NouveauColors.DarkIvoryText,
    surfaceVariant = NouveauColors.DarkLagoonSurfaceVariant,
    onSurfaceVariant = NouveauColors.DarkMutedText,
    outline = NouveauColors.DarkGoldOutline,
    outlineVariant = NouveauColors.DarkSoftOutlineVariant,
    error = NouveauColors.DarkError,
    onError = NouveauColors.DarkOnError,
    errorContainer = NouveauColors.DarkErrorContainer,
    onErrorContainer = NouveauColors.DarkOnErrorContainer,
    surfaceBright = NouveauColors.DarkLagoonSurfaceVariant,
    surfaceDim = NouveauColors.DarkLagoonSurface,
    surfaceContainerLowest = NouveauColors.DarkLagoonSurface,
    surfaceContainerLow = NouveauColors.DarkLagoonSurface,
    surfaceContainer = NouveauColors.DarkLagoonSurfaceVariant,
    surfaceContainerHigh = NouveauColors.DarkLagoonSurfaceVariant,
    surfaceContainerHighest = NouveauColors.DarkLagoonSurfaceVariant
)
