package com.hkm.stickhub.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/**
 * Batch-A theme tokens: Aurora, Synthwave, Gatsby, Ukiyo, Pixel.
 * Every scheme carries explicit opaque surface-container roles so
 * ModalBottomSheet / AlertDialog never render transparent.
 */

// ---------------------------------------------------------------- Aurora ---
object AuroraColors {
    val LightDawnBackground = Color(0xFFF4F6FF)
    val LightCloudSurface = Color(0xFFFFFFFF)
    val LightMistSurfaceVariant = Color(0xFFE7ECFF)
    val LightAuroraBluePrimary = Color(0xFF005FCE)
    val LightOnPrimary = Color(0xFFFFFFFF)
    val LightSkyPrimaryContainer = Color(0xFFDCE8FF)
    val LightOnSkyContainer = Color(0xFF12305E)
    val LightMagentaSecondary = Color(0xFFC2147A)
    val LightOnSecondary = Color(0xFFFFFFFF)
    val LightPetalSecondaryContainer = Color(0xFFFAD9EC)
    val LightOnSecondaryContainer = Color(0xFF57103C)
    val LightLagoonTertiary = Color(0xFF007A87)
    val LightOnTertiary = Color(0xFFFFFFFF)
    val LightFoamTertiaryContainer = Color(0xFFC9F2F5)
    val LightOnTertiaryContainer = Color(0xFF063B40)
    val LightNightText = Color(0xFF131A2A)
    val LightMutedText = Color(0xFF5A6478)
    val LightIrisOutline = Color(0xFF93A5D6)
    val LightSoftOutlineVariant = Color(0xFFD3DDF4)
    val LightError = Color(0xFFC62828)
    val LightOnError = Color(0xFFFFFFFF)
    val LightErrorContainer = Color(0xFFF5D5D5)
    val LightOnErrorContainer = Color(0xFF410002)

    val DarkNightBackground = Color(0xFF0A0F24)
    val DarkNightSurface = Color(0xFF111736)
    val DarkNightSurfaceVariant = Color(0xFF1B2350)
    val DarkSkyPrimary = Color(0xFF6BB8FF)
    val DarkOnPrimary = Color(0xFF0A0F24)
    val DarkNavyPrimaryContainer = Color(0xFF24407F)
    val DarkOnPrimaryContainer = Color(0xFFD6E6FF)
    val DarkMagentaSecondary = Color(0xFFFF5EB0)
    val DarkOnSecondary = Color(0xFF2A0A1E)
    val DarkPlumSecondaryContainer = Color(0xFF6E1E4E)
    val DarkOnSecondaryContainer = Color(0xFFFFD3E9)
    val DarkCyanTertiary = Color(0xFF4DE3E3)
    val DarkOnTertiary = Color(0xFF063B40)
    val DarkDeepTertiaryContainer = Color(0xFF0E4A4E)
    val DarkOnTertiaryContainer = Color(0xFFC9F2F5)
    val DarkStarText = Color(0xFFEAF0FF)
    val DarkMutedText = Color(0xFF9AA6C8)
    val DarkIrisOutline = Color(0xFF46568E)
    val DarkSoftOutlineVariant = Color(0xFF2A3560)
    val DarkError = Color(0xFFFF6B6B)
    val DarkOnError = Color(0xFF3A0E0B)
    val DarkErrorContainer = Color(0xFF5C2222)
    val DarkOnErrorContainer = Color(0xFFFFD9D9)
}

val AuroraLightColorScheme: ColorScheme = lightColorScheme(
    primary = AuroraColors.LightAuroraBluePrimary,
    onPrimary = AuroraColors.LightOnPrimary,
    primaryContainer = AuroraColors.LightSkyPrimaryContainer,
    onPrimaryContainer = AuroraColors.LightOnSkyContainer,
    secondary = AuroraColors.LightMagentaSecondary,
    onSecondary = AuroraColors.LightOnSecondary,
    secondaryContainer = AuroraColors.LightPetalSecondaryContainer,
    onSecondaryContainer = AuroraColors.LightOnSecondaryContainer,
    tertiary = AuroraColors.LightLagoonTertiary,
    onTertiary = AuroraColors.LightOnTertiary,
    tertiaryContainer = AuroraColors.LightFoamTertiaryContainer,
    onTertiaryContainer = AuroraColors.LightOnTertiaryContainer,
    background = AuroraColors.LightDawnBackground,
    onBackground = AuroraColors.LightNightText,
    surface = AuroraColors.LightCloudSurface,
    onSurface = AuroraColors.LightNightText,
    surfaceVariant = AuroraColors.LightMistSurfaceVariant,
    onSurfaceVariant = AuroraColors.LightMutedText,
    outline = AuroraColors.LightIrisOutline,
    outlineVariant = AuroraColors.LightSoftOutlineVariant,
    error = AuroraColors.LightError,
    onError = AuroraColors.LightOnError,
    errorContainer = AuroraColors.LightErrorContainer,
    onErrorContainer = AuroraColors.LightOnErrorContainer,
    surfaceBright = AuroraColors.LightCloudSurface,
    surfaceDim = AuroraColors.LightMistSurfaceVariant,
    surfaceContainerLowest = AuroraColors.LightCloudSurface,
    surfaceContainerLow = AuroraColors.LightCloudSurface,
    surfaceContainer = AuroraColors.LightMistSurfaceVariant,
    surfaceContainerHigh = AuroraColors.LightMistSurfaceVariant,
    surfaceContainerHighest = AuroraColors.LightMistSurfaceVariant
)

val AuroraDarkColorScheme: ColorScheme = darkColorScheme(
    primary = AuroraColors.DarkSkyPrimary,
    onPrimary = AuroraColors.DarkOnPrimary,
    primaryContainer = AuroraColors.DarkNavyPrimaryContainer,
    onPrimaryContainer = AuroraColors.DarkOnPrimaryContainer,
    secondary = AuroraColors.DarkMagentaSecondary,
    onSecondary = AuroraColors.DarkOnSecondary,
    secondaryContainer = AuroraColors.DarkPlumSecondaryContainer,
    onSecondaryContainer = AuroraColors.DarkOnSecondaryContainer,
    tertiary = AuroraColors.DarkCyanTertiary,
    onTertiary = AuroraColors.DarkOnTertiary,
    tertiaryContainer = AuroraColors.DarkDeepTertiaryContainer,
    onTertiaryContainer = AuroraColors.DarkOnTertiaryContainer,
    background = AuroraColors.DarkNightBackground,
    onBackground = AuroraColors.DarkStarText,
    surface = AuroraColors.DarkNightSurface,
    onSurface = AuroraColors.DarkStarText,
    surfaceVariant = AuroraColors.DarkNightSurfaceVariant,
    onSurfaceVariant = AuroraColors.DarkMutedText,
    outline = AuroraColors.DarkIrisOutline,
    outlineVariant = AuroraColors.DarkSoftOutlineVariant,
    error = AuroraColors.DarkError,
    onError = AuroraColors.DarkOnError,
    errorContainer = AuroraColors.DarkErrorContainer,
    onErrorContainer = AuroraColors.DarkOnErrorContainer,
    surfaceBright = AuroraColors.DarkNightSurfaceVariant,
    surfaceDim = AuroraColors.DarkNightSurface,
    surfaceContainerLowest = AuroraColors.DarkNightSurface,
    surfaceContainerLow = AuroraColors.DarkNightSurface,
    surfaceContainer = AuroraColors.DarkNightSurfaceVariant,
    surfaceContainerHigh = AuroraColors.DarkNightSurfaceVariant,
    surfaceContainerHighest = AuroraColors.DarkNightSurfaceVariant
)

// ------------------------------------------------------------- Synthwave ---
object SynthwaveColors {
    val LightLilacBackground = Color(0xFFF1EAFB)
    val LightChromeSurface = Color(0xFFFFFFFF)
    val LightHazeSurfaceVariant = Color(0xFFE2D5F8)
    val LightUltravioletPrimary = Color(0xFF5D34D0)
    val LightOnPrimary = Color(0xFFFFFFFF)
    val LightLavenderPrimaryContainer = Color(0xFFDCD0F7)
    val LightOnLavenderContainer = Color(0xFF2E1A66)
    val LightHotPinkSecondary = Color(0xFFC4005A)
    val LightOnSecondary = Color(0xFFFFFFFF)
    val LightCandySecondaryContainer = Color(0xFFF7C9E2)
    val LightOnSecondaryContainer = Color(0xFF4E0A2E)
    val LightLaserBlueTertiary = Color(0xFF0066CC)
    val LightOnTertiary = Color(0xFFFFFFFF)
    val LightIceTertiaryContainer = Color(0xFFC9E6FA)
    val LightOnTertiaryContainer = Color(0xFF0A2E52)
    val LightInkText = Color(0xFF1A1A2E)
    val LightMutedText = Color(0xFF5F5B7A)
    val LightNeonOutline = Color(0xFF7A68B0)
    val LightSoftOutlineVariant = Color(0xFFD5C9F0)
    val LightError = Color(0xFFC2263C)
    val LightOnError = Color(0xFFFFFFFF)
    val LightErrorContainer = Color(0xFFF6D2D8)
    val LightOnErrorContainer = Color(0xFF410002)

    val DarkVoidBackground = Color(0xFF0D0D1A)
    val DarkDeckSurface = Color(0xFF1A1A2E)
    val DarkDeckSurfaceVariant = Color(0xFF252542)
    val DarkNeonBluePrimary = Color(0xFF3D9BFF)
    val DarkOnPrimary = Color(0xFF0D0D1A)
    val DarkAbyssPrimaryContainer = Color(0xFF14305C)
    val DarkOnPrimaryContainer = Color(0xFFC9E6FF)
    val DarkHotPinkSecondary = Color(0xFFFF4D9A)
    val DarkOnSecondary = Color(0xFF2A0A1C)
    val DarkMaroonSecondaryContainer = Color(0xFF5E1039)
    val DarkOnSecondaryContainer = Color(0xFFFFD3E8)
    val DarkCyanTertiary = Color(0xFF45E8E8)
    val DarkOnTertiary = Color(0xFF063B40)
    val DarkReefTertiaryContainer = Color(0xFF0B3F42)
    val DarkOnTertiaryContainer = Color(0xFFC9F5F5)
    val DarkStaticText = Color(0xFFEDEBFF)
    val DarkMutedText = Color(0xFF9C96C4)
    val DarkNeonOutline = Color(0xFF5A56A8)
    val DarkSoftOutlineVariant = Color(0xFF2E2C5E)
    val DarkError = Color(0xFFFF6B7A)
    val DarkOnError = Color(0xFF3A0E0B)
    val DarkErrorContainer = Color(0xFF5C2222)
    val DarkOnErrorContainer = Color(0xFFFFD9D9)
}

val SynthwaveLightColorScheme: ColorScheme = lightColorScheme(
    primary = SynthwaveColors.LightUltravioletPrimary,
    onPrimary = SynthwaveColors.LightOnPrimary,
    primaryContainer = SynthwaveColors.LightLavenderPrimaryContainer,
    onPrimaryContainer = SynthwaveColors.LightOnLavenderContainer,
    secondary = SynthwaveColors.LightHotPinkSecondary,
    onSecondary = SynthwaveColors.LightOnSecondary,
    secondaryContainer = SynthwaveColors.LightCandySecondaryContainer,
    onSecondaryContainer = SynthwaveColors.LightOnSecondaryContainer,
    tertiary = SynthwaveColors.LightLaserBlueTertiary,
    onTertiary = SynthwaveColors.LightOnTertiary,
    tertiaryContainer = SynthwaveColors.LightIceTertiaryContainer,
    onTertiaryContainer = SynthwaveColors.LightOnTertiaryContainer,
    background = SynthwaveColors.LightLilacBackground,
    onBackground = SynthwaveColors.LightInkText,
    surface = SynthwaveColors.LightChromeSurface,
    onSurface = SynthwaveColors.LightInkText,
    surfaceVariant = SynthwaveColors.LightHazeSurfaceVariant,
    onSurfaceVariant = SynthwaveColors.LightMutedText,
    outline = SynthwaveColors.LightNeonOutline,
    outlineVariant = SynthwaveColors.LightSoftOutlineVariant,
    error = SynthwaveColors.LightError,
    onError = SynthwaveColors.LightOnError,
    errorContainer = SynthwaveColors.LightErrorContainer,
    onErrorContainer = SynthwaveColors.LightOnErrorContainer,
    surfaceBright = SynthwaveColors.LightChromeSurface,
    surfaceDim = SynthwaveColors.LightHazeSurfaceVariant,
    surfaceContainerLowest = SynthwaveColors.LightChromeSurface,
    surfaceContainerLow = SynthwaveColors.LightChromeSurface,
    surfaceContainer = SynthwaveColors.LightHazeSurfaceVariant,
    surfaceContainerHigh = SynthwaveColors.LightHazeSurfaceVariant,
    surfaceContainerHighest = SynthwaveColors.LightHazeSurfaceVariant
)

val SynthwaveDarkColorScheme: ColorScheme = darkColorScheme(
    primary = SynthwaveColors.DarkNeonBluePrimary,
    onPrimary = SynthwaveColors.DarkOnPrimary,
    primaryContainer = SynthwaveColors.DarkAbyssPrimaryContainer,
    onPrimaryContainer = SynthwaveColors.DarkOnPrimaryContainer,
    secondary = SynthwaveColors.DarkHotPinkSecondary,
    onSecondary = SynthwaveColors.DarkOnSecondary,
    secondaryContainer = SynthwaveColors.DarkMaroonSecondaryContainer,
    onSecondaryContainer = SynthwaveColors.DarkOnSecondaryContainer,
    tertiary = SynthwaveColors.DarkCyanTertiary,
    onTertiary = SynthwaveColors.DarkOnTertiary,
    tertiaryContainer = SynthwaveColors.DarkReefTertiaryContainer,
    onTertiaryContainer = SynthwaveColors.DarkOnTertiaryContainer,
    background = SynthwaveColors.DarkVoidBackground,
    onBackground = SynthwaveColors.DarkStaticText,
    surface = SynthwaveColors.DarkDeckSurface,
    onSurface = SynthwaveColors.DarkStaticText,
    surfaceVariant = SynthwaveColors.DarkDeckSurfaceVariant,
    onSurfaceVariant = SynthwaveColors.DarkMutedText,
    outline = SynthwaveColors.DarkNeonOutline,
    outlineVariant = SynthwaveColors.DarkSoftOutlineVariant,
    error = SynthwaveColors.DarkError,
    onError = SynthwaveColors.DarkOnError,
    errorContainer = SynthwaveColors.DarkErrorContainer,
    onErrorContainer = SynthwaveColors.DarkOnErrorContainer,
    surfaceBright = SynthwaveColors.DarkDeckSurfaceVariant,
    surfaceDim = SynthwaveColors.DarkDeckSurface,
    surfaceContainerLowest = SynthwaveColors.DarkDeckSurface,
    surfaceContainerLow = SynthwaveColors.DarkDeckSurface,
    surfaceContainer = SynthwaveColors.DarkDeckSurfaceVariant,
    surfaceContainerHigh = SynthwaveColors.DarkDeckSurfaceVariant,
    surfaceContainerHighest = SynthwaveColors.DarkDeckSurfaceVariant
)

// ---------------------------------------------------------------- Gatsby ---
object GatsbyColors {
    val LightChampagneBackground = Color(0xFFF7EEDC)
    val LightBallroomSurface = Color(0xFFFFFDF6)
    val LightGiltSurfaceVariant = Color(0xFFEFE0C2)
    val LightTuxedoPrimary = Color(0xFF17130E)
    val LightOnPrimary = Color(0xFFF7EEDC)
    val LightGoldPrimaryContainer = Color(0xFFD4AF37)
    val LightOnGoldContainer = Color(0xFF241A05)
    val LightBronzeSecondary = Color(0xFF8A6D2F)
    val LightOnSecondary = Color(0xFFFFFDF6)
    val LightSateenSecondaryContainer = Color(0xFFE9D9AE)
    val LightOnSecondaryContainer = Color(0xFF3A2C08)
    val LightEmeraldTertiary = Color(0xFF2F5249)
    val LightOnTertiary = Color(0xFFFFFDF6)
    val LightJadeTertiaryContainer = Color(0xFFCBDDD3)
    val LightOnTertiaryContainer = Color(0xFF0E2A22)
    val LightInkText = Color(0xFF1A1512)
    val LightMutedText = Color(0xFF6E6250)
    val LightGoldOutline = Color(0xFFA8862C)
    val LightSoftOutlineVariant = Color(0xFFE2D2A4)
    val LightError = Color(0xFFA63A32)
    val LightOnError = Color(0xFFFFFDF6)
    val LightErrorContainer = Color(0xFFF5D5D1)
    val LightOnErrorContainer = Color(0xFF410002)

    val DarkNoirBackground = Color(0xFF0B0B0E)
    val DarkVelvetSurface = Color(0xFF141416)
    val DarkVelvetSurfaceVariant = Color(0xFF1E1E24)
    val DarkGoldPrimary = Color(0xFFD4AF37)
    val DarkOnPrimary = Color(0xFF17130E)
    val DarkBronzePrimaryContainer = Color(0xFF52400F)
    val DarkOnPrimaryContainer = Color(0xFFF2E6CF)
    val DarkFoilSecondary = Color(0xFFC5A059)
    val DarkOnSecondary = Color(0xFF17130E)
    val DarkAntiqueSecondaryContainer = Color(0xFF3A2E14)
    val DarkOnSecondaryContainer = Color(0xFFEDDCB8)
    val DarkClaretTertiary = Color(0xFFB03A3A)
    val DarkOnTertiary = Color(0xFFFFF3E8)
    val DarkWineTertiaryContainer = Color(0xFF471414)
    val DarkOnTertiaryContainer = Color(0xFFF2C9C9)
    val DarkCreamText = Color(0xFFF2E6CF)
    val DarkMutedText = Color(0xFFB8A98A)
    val DarkGoldOutline = Color(0xFFC5A059)
    val DarkSoftOutlineVariant = Color(0xFF3A3325)
    val DarkError = Color(0xFFE89890)
    val DarkOnError = Color(0xFF3A0E0B)
    val DarkErrorContainer = Color(0xFF5C2222)
    val DarkOnErrorContainer = Color(0xFFFFD9D9)
}

val GatsbyLightColorScheme: ColorScheme = lightColorScheme(
    primary = GatsbyColors.LightTuxedoPrimary,
    onPrimary = GatsbyColors.LightOnPrimary,
    primaryContainer = GatsbyColors.LightGoldPrimaryContainer,
    onPrimaryContainer = GatsbyColors.LightOnGoldContainer,
    secondary = GatsbyColors.LightBronzeSecondary,
    onSecondary = GatsbyColors.LightOnSecondary,
    secondaryContainer = GatsbyColors.LightSateenSecondaryContainer,
    onSecondaryContainer = GatsbyColors.LightOnSecondaryContainer,
    tertiary = GatsbyColors.LightEmeraldTertiary,
    onTertiary = GatsbyColors.LightOnTertiary,
    tertiaryContainer = GatsbyColors.LightJadeTertiaryContainer,
    onTertiaryContainer = GatsbyColors.LightOnTertiaryContainer,
    background = GatsbyColors.LightChampagneBackground,
    onBackground = GatsbyColors.LightInkText,
    surface = GatsbyColors.LightBallroomSurface,
    onSurface = GatsbyColors.LightInkText,
    surfaceVariant = GatsbyColors.LightGiltSurfaceVariant,
    onSurfaceVariant = GatsbyColors.LightMutedText,
    outline = GatsbyColors.LightGoldOutline,
    outlineVariant = GatsbyColors.LightSoftOutlineVariant,
    error = GatsbyColors.LightError,
    onError = GatsbyColors.LightOnError,
    errorContainer = GatsbyColors.LightErrorContainer,
    onErrorContainer = GatsbyColors.LightOnErrorContainer,
    surfaceBright = GatsbyColors.LightBallroomSurface,
    surfaceDim = GatsbyColors.LightGiltSurfaceVariant,
    surfaceContainerLowest = GatsbyColors.LightBallroomSurface,
    surfaceContainerLow = GatsbyColors.LightBallroomSurface,
    surfaceContainer = GatsbyColors.LightGiltSurfaceVariant,
    surfaceContainerHigh = GatsbyColors.LightGiltSurfaceVariant,
    surfaceContainerHighest = GatsbyColors.LightGiltSurfaceVariant
)

val GatsbyDarkColorScheme: ColorScheme = darkColorScheme(
    primary = GatsbyColors.DarkGoldPrimary,
    onPrimary = GatsbyColors.DarkOnPrimary,
    primaryContainer = GatsbyColors.DarkBronzePrimaryContainer,
    onPrimaryContainer = GatsbyColors.DarkOnPrimaryContainer,
    secondary = GatsbyColors.DarkFoilSecondary,
    onSecondary = GatsbyColors.DarkOnSecondary,
    secondaryContainer = GatsbyColors.DarkAntiqueSecondaryContainer,
    onSecondaryContainer = GatsbyColors.DarkOnSecondaryContainer,
    tertiary = GatsbyColors.DarkClaretTertiary,
    onTertiary = GatsbyColors.DarkOnTertiary,
    tertiaryContainer = GatsbyColors.DarkWineTertiaryContainer,
    onTertiaryContainer = GatsbyColors.DarkOnTertiaryContainer,
    background = GatsbyColors.DarkNoirBackground,
    onBackground = GatsbyColors.DarkCreamText,
    surface = GatsbyColors.DarkVelvetSurface,
    onSurface = GatsbyColors.DarkCreamText,
    surfaceVariant = GatsbyColors.DarkVelvetSurfaceVariant,
    onSurfaceVariant = GatsbyColors.DarkMutedText,
    outline = GatsbyColors.DarkGoldOutline,
    outlineVariant = GatsbyColors.DarkSoftOutlineVariant,
    error = GatsbyColors.DarkError,
    onError = GatsbyColors.DarkOnError,
    errorContainer = GatsbyColors.DarkErrorContainer,
    onErrorContainer = GatsbyColors.DarkOnErrorContainer,
    surfaceBright = GatsbyColors.DarkVelvetSurfaceVariant,
    surfaceDim = GatsbyColors.DarkVelvetSurface,
    surfaceContainerLowest = GatsbyColors.DarkVelvetSurface,
    surfaceContainerLow = GatsbyColors.DarkVelvetSurface,
    surfaceContainer = GatsbyColors.DarkVelvetSurfaceVariant,
    surfaceContainerHigh = GatsbyColors.DarkVelvetSurfaceVariant,
    surfaceContainerHighest = GatsbyColors.DarkVelvetSurfaceVariant
)

// ----------------------------------------------------------------- Ukiyo ---
object UkiyoColors {
    val LightWashiBackground = Color(0xFFF0E3CE)
    val LightRiceSurface = Color(0xFFFAF3E6)
    val LightSandSurfaceVariant = Color(0xFFE4D3B8)
    val LightSumiPrimary = Color(0xFF26262F)
    val LightOnPrimary = Color(0xFFF0E3CE)
    val LightWavePrimaryContainer = Color(0xFFC9D9E4)
    val LightOnWaveContainer = Color(0xFF0D1B2A)
    val LightVermilionSecondary = Color(0xFFC74A28)
    val LightOnSecondary = Color(0xFFFAF3E6)
    val LightPersimmonSecondaryContainer = Color(0xFFF6CDBE)
    val LightOnSecondaryContainer = Color(0xFF471708)
    val LightPrussianTertiary = Color(0xFF0F5C88)
    val LightOnTertiary = Color(0xFFFAF3E6)
    val LightMistTertiaryContainer = Color(0xFFC7DFEC)
    val LightOnTertiaryContainer = Color(0xFF0B2A40)
    val LightInkText = Color(0xFF1C1C26)
    val LightMutedText = Color(0xFF6B6257)
    val LightSumiOutline = Color(0xFF3A3A48)
    val LightSoftOutlineVariant = Color(0xFFCBBFA8)
    val LightError = Color(0xFFA63A32)
    val LightOnError = Color(0xFFFAF3E6)
    val LightErrorContainer = Color(0xFFF5D5D1)
    val LightOnErrorContainer = Color(0xFF410002)

    val DarkSeaBackground = Color(0xFF0D1B2A)
    val DarkDeepSurface = Color(0xFF12263A)
    val DarkDeepSurfaceVariant = Color(0xFF1A3249)
    val DarkMoonPrimary = Color(0xFFF0E3CE)
    val DarkOnPrimary = Color(0xFF0D1B2A)
    val DarkIndigoPrimaryContainer = Color(0xFF2A4056)
    val DarkOnPrimaryContainer = Color(0xFFD8E2EA)
    val DarkVermilionSecondary = Color(0xFFF0704A)
    val DarkOnSecondary = Color(0xFF2A0E05)
    val DarkEmberSecondaryContainer = Color(0xFF5C2317)
    val DarkOnSecondaryContainer = Color(0xFFF6CDBE)
    val DarkOchreTertiary = Color(0xFFD8943A)
    val DarkOnTertiary = Color(0xFF2A1A05)
    val DarkBronzeTertiaryContainer = Color(0xFF4A2E0E)
    val DarkOnTertiaryContainer = Color(0xFFEFD9AC)
    val DarkPaperText = Color(0xFFEFE4D0)
    val DarkMutedText = Color(0xFFB3A48E)
    val DarkMistOutline = Color(0xFF8FA3B8)
    val DarkSoftOutlineVariant = Color(0xFF2A4056)
    val DarkError = Color(0xFFE89890)
    val DarkOnError = Color(0xFF3A0E0B)
    val DarkErrorContainer = Color(0xFF5C2222)
    val DarkOnErrorContainer = Color(0xFFFFD9D9)
}

val UkiyoLightColorScheme: ColorScheme = lightColorScheme(
    primary = UkiyoColors.LightSumiPrimary,
    onPrimary = UkiyoColors.LightOnPrimary,
    primaryContainer = UkiyoColors.LightWavePrimaryContainer,
    onPrimaryContainer = UkiyoColors.LightOnWaveContainer,
    secondary = UkiyoColors.LightVermilionSecondary,
    onSecondary = UkiyoColors.LightOnSecondary,
    secondaryContainer = UkiyoColors.LightPersimmonSecondaryContainer,
    onSecondaryContainer = UkiyoColors.LightOnSecondaryContainer,
    tertiary = UkiyoColors.LightPrussianTertiary,
    onTertiary = UkiyoColors.LightOnTertiary,
    tertiaryContainer = UkiyoColors.LightMistTertiaryContainer,
    onTertiaryContainer = UkiyoColors.LightOnTertiaryContainer,
    background = UkiyoColors.LightWashiBackground,
    onBackground = UkiyoColors.LightInkText,
    surface = UkiyoColors.LightRiceSurface,
    onSurface = UkiyoColors.LightInkText,
    surfaceVariant = UkiyoColors.LightSandSurfaceVariant,
    onSurfaceVariant = UkiyoColors.LightMutedText,
    outline = UkiyoColors.LightSumiOutline,
    outlineVariant = UkiyoColors.LightSoftOutlineVariant,
    error = UkiyoColors.LightError,
    onError = UkiyoColors.LightOnError,
    errorContainer = UkiyoColors.LightErrorContainer,
    onErrorContainer = UkiyoColors.LightOnErrorContainer,
    surfaceBright = UkiyoColors.LightRiceSurface,
    surfaceDim = UkiyoColors.LightSandSurfaceVariant,
    surfaceContainerLowest = UkiyoColors.LightRiceSurface,
    surfaceContainerLow = UkiyoColors.LightRiceSurface,
    surfaceContainer = UkiyoColors.LightSandSurfaceVariant,
    surfaceContainerHigh = UkiyoColors.LightSandSurfaceVariant,
    surfaceContainerHighest = UkiyoColors.LightSandSurfaceVariant
)

val UkiyoDarkColorScheme: ColorScheme = darkColorScheme(
    primary = UkiyoColors.DarkMoonPrimary,
    onPrimary = UkiyoColors.DarkOnPrimary,
    primaryContainer = UkiyoColors.DarkIndigoPrimaryContainer,
    onPrimaryContainer = UkiyoColors.DarkOnPrimaryContainer,
    secondary = UkiyoColors.DarkVermilionSecondary,
    onSecondary = UkiyoColors.DarkOnSecondary,
    secondaryContainer = UkiyoColors.DarkEmberSecondaryContainer,
    onSecondaryContainer = UkiyoColors.DarkOnSecondaryContainer,
    tertiary = UkiyoColors.DarkOchreTertiary,
    onTertiary = UkiyoColors.DarkOnTertiary,
    tertiaryContainer = UkiyoColors.DarkBronzeTertiaryContainer,
    onTertiaryContainer = UkiyoColors.DarkOnTertiaryContainer,
    background = UkiyoColors.DarkSeaBackground,
    onBackground = UkiyoColors.DarkPaperText,
    surface = UkiyoColors.DarkDeepSurface,
    onSurface = UkiyoColors.DarkPaperText,
    surfaceVariant = UkiyoColors.DarkDeepSurfaceVariant,
    onSurfaceVariant = UkiyoColors.DarkMutedText,
    outline = UkiyoColors.DarkMistOutline,
    outlineVariant = UkiyoColors.DarkSoftOutlineVariant,
    error = UkiyoColors.DarkError,
    onError = UkiyoColors.DarkOnError,
    errorContainer = UkiyoColors.DarkErrorContainer,
    onErrorContainer = UkiyoColors.DarkOnErrorContainer,
    surfaceBright = UkiyoColors.DarkDeepSurfaceVariant,
    surfaceDim = UkiyoColors.DarkDeepSurface,
    surfaceContainerLowest = UkiyoColors.DarkDeepSurface,
    surfaceContainerLow = UkiyoColors.DarkDeepSurface,
    surfaceContainer = UkiyoColors.DarkDeepSurfaceVariant,
    surfaceContainerHigh = UkiyoColors.DarkDeepSurfaceVariant,
    surfaceContainerHighest = UkiyoColors.DarkDeepSurfaceVariant
)

// ----------------------------------------------------------------- Pixel ---
object PixelColors {
    val LightAmberPaperBackground = Color(0xFFEFEAD6)
    val LightCartridgeSurface = Color(0xFFF7F2E2)
    val LightSandSurfaceVariant = Color(0xFFE2D6B8)
    val LightPhosphorDeepPrimary = Color(0xFF0B5A30)
    val LightOnPrimary = Color(0xFFF7F2E2)
    val LightPhosphorPrimaryContainer = Color(0xFFA8E6BC)
    val LightOnPhosphorContainer = Color(0xFF06331A)
    val LightCoinSlotSecondary = Color(0xFF8A5600)
    val LightOnSecondary = Color(0xFFF7F2E2)
    val LightCoinSecondaryContainer = Color(0xFFF5D48A)
    val LightOnSecondaryContainer = Color(0xFF3A2600)
    val LightPlayerTwoTertiary = Color(0xFF2456A8)
    val LightOnTertiary = Color(0xFFF7F2E2)
    val LightSkyTertiaryContainer = Color(0xFFC4D9F5)
    val LightOnTertiaryContainer = Color(0xFF10294F)
    val LightCabinetText = Color(0xFF1A2413)
    val LightMutedText = Color(0xFF6B7057)
    val LightJoystickOutline = Color(0xFF2E4A2E)
    val LightSoftOutlineVariant = Color(0xFFC9BE98)
    val LightError = Color(0xFFC22E22)
    val LightOnError = Color(0xFFF7F2E2)
    val LightErrorContainer = Color(0xFFF5CFC8)
    val LightOnErrorContainer = Color(0xFF410002)

    val DarkCabinetBackground = Color(0xFF0A0A0A)
    val DarkCabinetSurface = Color(0xFF101010)
    val DarkCabinetSurfaceVariant = Color(0xFF1A1A1A)
    val DarkPhosphorPrimary = Color(0xFF2CFF56)
    val DarkOnPrimary = Color(0xFF0A0A0A)
    val DarkDeepPhosphorContainer = Color(0xFF0E4A24)
    val DarkOnPrimaryContainer = Color(0xFFB9FFCE)
    val DarkAmberSecondary = Color(0xFFFFB200)
    val DarkOnSecondary = Color(0xFF0A0A0A)
    val DarkBronzeSecondaryContainer = Color(0xFF4A3200)
    val DarkOnSecondaryContainer = Color(0xFFFFE1A1)
    val DarkCoinTertiary = Color(0xFFFFD700)
    val DarkOnTertiary = Color(0xFF0A0A0A)
    val DarkVaultTertiaryContainer = Color(0xFF4A3D00)
    val DarkOnTertiaryContainer = Color(0xFFFFECA8)
    val DarkPhosphorText = Color(0xFFC9F5D4)
    val DarkMutedText = Color(0xFF7FA88C)
    val DarkPhosphorOutline = Color(0xFF27D94D)
    val DarkSoftOutlineVariant = Color(0xFF1E3A28)
    val DarkError = Color(0xFFFF5A4E)
    val DarkOnError = Color(0xFF0A0A0A)
    val DarkErrorContainer = Color(0xFF5C1A14)
    val DarkOnErrorContainer = Color(0xFFFFC9C2)
}

val PixelLightColorScheme: ColorScheme = lightColorScheme(
    primary = PixelColors.LightPhosphorDeepPrimary,
    onPrimary = PixelColors.LightOnPrimary,
    primaryContainer = PixelColors.LightPhosphorPrimaryContainer,
    onPrimaryContainer = PixelColors.LightOnPhosphorContainer,
    secondary = PixelColors.LightCoinSlotSecondary,
    onSecondary = PixelColors.LightOnSecondary,
    secondaryContainer = PixelColors.LightCoinSecondaryContainer,
    onSecondaryContainer = PixelColors.LightOnSecondaryContainer,
    tertiary = PixelColors.LightPlayerTwoTertiary,
    onTertiary = PixelColors.LightOnTertiary,
    tertiaryContainer = PixelColors.LightSkyTertiaryContainer,
    onTertiaryContainer = PixelColors.LightOnTertiaryContainer,
    background = PixelColors.LightAmberPaperBackground,
    onBackground = PixelColors.LightCabinetText,
    surface = PixelColors.LightCartridgeSurface,
    onSurface = PixelColors.LightCabinetText,
    surfaceVariant = PixelColors.LightSandSurfaceVariant,
    onSurfaceVariant = PixelColors.LightMutedText,
    outline = PixelColors.LightJoystickOutline,
    outlineVariant = PixelColors.LightSoftOutlineVariant,
    error = PixelColors.LightError,
    onError = PixelColors.LightOnError,
    errorContainer = PixelColors.LightErrorContainer,
    onErrorContainer = PixelColors.LightOnErrorContainer,
    surfaceBright = PixelColors.LightCartridgeSurface,
    surfaceDim = PixelColors.LightSandSurfaceVariant,
    surfaceContainerLowest = PixelColors.LightCartridgeSurface,
    surfaceContainerLow = PixelColors.LightCartridgeSurface,
    surfaceContainer = PixelColors.LightSandSurfaceVariant,
    surfaceContainerHigh = PixelColors.LightSandSurfaceVariant,
    surfaceContainerHighest = PixelColors.LightSandSurfaceVariant
)

val PixelDarkColorScheme: ColorScheme = darkColorScheme(
    primary = PixelColors.DarkPhosphorPrimary,
    onPrimary = PixelColors.DarkOnPrimary,
    primaryContainer = PixelColors.DarkDeepPhosphorContainer,
    onPrimaryContainer = PixelColors.DarkOnPrimaryContainer,
    secondary = PixelColors.DarkAmberSecondary,
    onSecondary = PixelColors.DarkOnSecondary,
    secondaryContainer = PixelColors.DarkBronzeSecondaryContainer,
    onSecondaryContainer = PixelColors.DarkOnSecondaryContainer,
    tertiary = PixelColors.DarkCoinTertiary,
    onTertiary = PixelColors.DarkOnTertiary,
    tertiaryContainer = PixelColors.DarkVaultTertiaryContainer,
    onTertiaryContainer = PixelColors.DarkOnTertiaryContainer,
    background = PixelColors.DarkCabinetBackground,
    onBackground = PixelColors.DarkPhosphorText,
    surface = PixelColors.DarkCabinetSurface,
    onSurface = PixelColors.DarkPhosphorText,
    surfaceVariant = PixelColors.DarkCabinetSurfaceVariant,
    onSurfaceVariant = PixelColors.DarkMutedText,
    outline = PixelColors.DarkPhosphorOutline,
    outlineVariant = PixelColors.DarkSoftOutlineVariant,
    error = PixelColors.DarkError,
    onError = PixelColors.DarkOnError,
    errorContainer = PixelColors.DarkErrorContainer,
    onErrorContainer = PixelColors.DarkOnErrorContainer,
    surfaceBright = PixelColors.DarkCabinetSurfaceVariant,
    surfaceDim = PixelColors.DarkCabinetSurface,
    surfaceContainerLowest = PixelColors.DarkCabinetSurface,
    surfaceContainerLow = PixelColors.DarkCabinetSurface,
    surfaceContainer = PixelColors.DarkCabinetSurfaceVariant,
    surfaceContainerHigh = PixelColors.DarkCabinetSurfaceVariant,
    surfaceContainerHighest = PixelColors.DarkCabinetSurfaceVariant
)
